[package]
name = "post-image-in-intervals"
version = "0.1.0"
edition = "2021"

[features]
use-webcam = []

[dependencies]
html-strong-homepage = { path = "../.." }

image = "0.24.2"
reqwest = { version = "0.11.11", features = ["blocking"] }
tracing = "0.1.35"
tracing-subscriber = "0.3.14"
